name: RPGHealthPlus
main: me.Bleuzen.RPGHealthPlus.Main
version: 1.4.9
api-version: 1.16
author: Bleuzen
softdepend: [HolographicDisplays]
description: Adds the ability to levelup your health!
commands:
  rpghp:
    description: This is the main command for admins. 
  hp:
    description: Shows your progress to the next level.
